import { createContext, useContext, useState, useEffect } from "react";

const AppContext = createContext();

export function AppProvider({ children }) {
  const [dark, setDark] = useState(() => localStorage.getItem("nt_dark") === "true");
  const [lang, setLang] = useState(() => localStorage.getItem("nt_lang") || "uz");

  useEffect(() => {
    localStorage.setItem("nt_dark", dark);
    if (dark) document.documentElement.setAttribute("data-theme", "dark");
    else document.documentElement.removeAttribute("data-theme");
  }, [dark]);

  useEffect(() => { localStorage.setItem("nt_lang", lang); }, [lang]);

  const toggleDark = () => setDark(p => !p);
  const toggleLang = () => setLang(p => p === "uz" ? "ru" : "uz");

  const T = {
    uz: {
      // Login
      loginLabel: "Login",
      loginPlaceholder: "Loginni kiriting",
      passwordLabel: "Parol",
      passwordPlaceholder: "Parolni kiriting",
      loginBtn: "Kirish",
      loginError: "Login yoki parol noto'g'ri",
      loginSuccess: "Muvaffaqiyatli kirildi",
      copyright: "Copyright © 2024 Najot Ta'lim",
      logout: "Chiqish",
      loading: "Yuklanmoqda",

      // Sidebar / Nav menu
      menu: ["Asosiy", "O'qituvchilar", "Guruhlar", "Talabalar", "Sovg'alar", "Boshqarish"],
      subscription: "Obuna",
      subscriptionExpired: "Obunangiz tugagan",
      subscriptionRenew: "Obunani yangilash",
      darkMode: "Qorong'u",
      lightMode: "Yorug'",

      // Management sidebar
      courses: "Kurslar",
      rooms: "Xonalar",
      staff: "Xodimlar",
      coin: "Coin",
      sendMessage: "Xabar Yuborish",

      // Common buttons
      add: "Qo'shish",
      save: "Saqlash",
      cancel: "Bekor qilish",
      edit: "Tahrirlash",
      delete: "O'chirish",
      archive: "Arxiv",
      restore: "Tiklash",
      search: "Qidirish",
      filter: "Filter",
      refresh: "Yangilash",
      send: "Yuborish",
      sending: "Yuborilmoqda...",
      yes: "Ha",
      close: "Yopish",
      back: "Orqaga",
      statistics: "Statistika",
      previous: "← Oldingi",
      next: "Keyingi →",

      // Confirm dialog
      confirmDelete: "O'chirishni tasdiqlash",
      confirmDeleteMsg: "Rostdan ham o'chirishni hohlaysizmi?",

      // Common labels
      name: "Nomi",
      fullName: "F.I.O",
      phone: "Telefon",
      email: "Email",
      address: "Manzil",
      password: "Parol",
      birthDate: "Tug'ilgan sana",
      group: "Guruh",
      groups: "Guruhlar",
      date: "Sana",
      actions: "Amallar",
      status: "Status",
      active: "FAOL",
      inactive: "NOFAOL",
      noData: "Ma'lumot mavjud emas",
      loading2: "Yuklanmoqda...",

      // Dashboard
      dashboardGreeting: "Salom",
      dashboardWelcome: "Najot CRM platformasiga xush kelibsiz!",
      activeStudents: "Faol talabalar",
      groupsCount: "Guruhlar",
      monthPayments: "Joriy oy to'lovlar",
      debtors: "Qarzdorlar",
      frozen: "Muzlatilganlar",
      archived: "Arxivdagilar",
      monthlyPayments: "Joriy oy uchun to'lovlar",
      annualProfit: "Yillik Foyda",
      schedule: "Dars jadvali",

      // Teachers
      teachersTitle: "O'qituvchilar",
      teachersSubtitle: "Ushbu sahifada siz o'qituvchilar ro'yxatini va ularning ma'lumotlarini topasiz.",
      addTeacher: "O'qituvchi qo'shish",
      teacherAdded: "O'qituvchi qo'shildi",
      teacherUpdated: "O'qituvchi yangilandi",
      teacherDeleted: "O'qituvchi o'chirildi",
      teacherDeleteConfirm: "O'qituvchini o'chirish",
      teacherDeleteMsg: "Rostdan ham bu o'qituvchini o'chirishni hohlaysizmi?",
      archiveTeachers: "Arxivlangan o'qituvchilar",
      noArchivedTeachers: "Arxivlangan o'qituvchilar yo'q",
      teacherModalAdd: "O'qituvchi qo'shish",
      teacherModalEdit: "O'qituvchini tahrirlash",
      teacherModalAddSubtitle: "Bu yerda siz yangi o'qituvchi qo'shishingiz mumkin.",
      teacherModalEditSubtitle: "Bu yerda o'qituvchini yangilashingiz mumkin.",

      // Students
      studentsTitle: "Talabalar",
      studentsSubtitle: "Ushbu sahifada talabalar ro'yxati va ularning ma'lumotlari keltirilgan.",
      addStudent: "Talaba qo'shish",
      studentAdded: "Talaba qo'shildi",
      studentUpdated: "Talaba yangilandi",
      studentDeleted: "Talaba o'chirildi",
      studentDeleteConfirm: "Talabani o'chirish",
      studentDeleteMsg: "Rostdan ham bu talabani o'chirishni hohlaysizmi?",
      archiveStudents: "Arxivlangan talabalar",
      noArchivedStudents: "Arxivlangan talabalar yo'q",
      studentModalAdd: "Talaba qo'shish",
      studentModalEdit: "Talabani tahrirlash",

      // Groups
      groupsTitle: "Guruhlar",
      addGroup: "Guruh qo'shish",
      groupActivated: "Guruh faollashtirildi",
      groupDeactivated: "Guruh nofaol qilindi",
      groupDeleteConfirm: "Guruhni o'chirish",
      groupDeleteMsg: "Rostdan ham bu guruhni o'chirishni hohlaysizmi?",
      archiveGroups: "Arxivlangan guruhlar",
      archiveGroupsSubtitle: "Arxivlangan guruhlar ro'yxati",
      groupModalAdd: "Guruh qo'shish",
      groupModalAddSubtitle: "Yangi guruh yaratish uchun quyidagi ma'lumotlarni kiriting.",
      course: "Kurs",
      duration: "Davomiyligi",
      lessonTime: "Dars vaqti",
      room: "Xona",
      teacher: "O'qituvchi",
      students2: "Talabalar",
      teacher2: "O'qituvchi",
      maxStudents: "Max talabalar",
      description: "Tavsif",
      startDate: "Boshlash sanasi",
      daysOfWeek: "Dars kunlari",
      startTime: "Dars vaqti",
      groupName: "Guruh nomi",
      courseName: "Kurs nomi",
      roomName: "Xona nomi",
      courseDuration: "Kurs davomiyligi",
      lessonDuration: "Dars davomiyligi",
      studentCount: "Talabalar soni",
      mentors: "Mentorlar",
      groupParams: "Guruh parametrlari",
      direction: "Yo'nalish",
      avgAge: "O'rtacha yosh",
      capacity: "Sig'imi",
      currentStudents: "Hozirgi o'quvchilar",
      totalLessons: "Darslar soni (Jami)",
      lessonSchedule: "Dars jadvali",
      currentMonth: "Joriy oy",
      showAll: "Barchasini ko'rish",
      hide: "Yopish",
      showMore: "Yana ko'rsatish",
      addStudentToGroup: "Talaba qo'shish",
      addStudentToGroupSubtitle: "Guruhga talabalarni tanlang",
      alreadyInGroup: "Guruhda",
      studentAdding: "Qo'shilmoqda...",
      studentAddSuccess: "ta talaba muvaffaqiyatli qo'shildi",
      studentAddError: "Talaba qo'shishda xatolik yuz berdi",
      mentors: "Mentorlar",
      noStudentsAdded: "Talaba qo'shilmagan",

      // Group Detail tabs
      groupInfo: "Ma'lumotlar",
      groupLessons: "Guruh darsliklari",
      academicAttendance: "Akademik davomati",
      homework: "Uyga vazifa",
      videos: "Videolar",
      exams: "Imtihonlar",
      journal: "Jurnal",

      // Homework
      homeworkTitle: "Uyga vazifa",
      topic: "Mavzu",
      deadline: "Tugash vaqti",
      givenTime: "Berilgan vaqt",
      lessonDate: "Dars sanasi",
      studentName: "O'quvchi ismi",
      submittedAt: "Uyga vazifa jo'natilgan vaqt",
      pending: "Kutayotganlar",
      rejected: "Qaytarilganlar",
      accepted: "Qabul qilinganlar",
      notDone: "Bajarilmagan",
      checkHomework: "Uyga vazifa tekshirish",
      homeworkDesc: "Uy vazifasi",
      comment: "Izoh",
      commentPlaceholder: "O'quvchiga izoh yozing (ixtiyoriy)",
      ball: "Ball",
      passScore: "O'tish bali: 60",
      acceptInfo: "60–100 ball — Qabul qilinadi.",
      rejectInfo: "0–59 ball — Qaytariladi.",
      studentComment: "O'quvchi izohi:",
      uploadedFiles: "Yuklangan fayllar:",
      submittedTime: "Topshirilgan vaqt",
      filesCount: "Fayllar soni",
      loadError: "Ma'lumot yuklanmadi. Sahifani yangilang.",
      serverError: "Server xatosi",
      errorOccurred: "Xatolik yuz berdi. Qaytadan urinib ko'ring.",

      // Videos
      videoName: "Video nomi",
      lessonName: "Dars nomi",
      addedTime: "Qo'shilgan",
      size: "Hajmi",
      noVideos: "Videolar topilmadi",
      addVideo: "Video qo'shish",
      uploadVideo: "Videofaylni yuklash uchun bosing yoki faylni shu yerga olib keling",
      uploadFormats: ".mp4, .webm, .mpeg, .avi, .mkv, .m4v, .mov",
      uploadFiles: "Fayllarni yuklash",
      uploading: "Yuklanmoqda...",
      selectLesson: "Darsni tanlang",

      // Lessons
      lessonInfo: "Ma'lumot",
      lessonDay: "Dars kuni",
      lessonStatus: "Holat",
      lessonNotDone: "Dars o'tilmagan",
      attendance: "Yo'qlama va mavzu kiritish",
      byPlan: "O'quv reja bo'yicha",
      other: "Boshqa",
      topicLabel: "Mavzu",
      topicPlaceholder: "Mavzuni kiriting...",
      selectTopic: "Mavzuni tanlang...",
      lessonDescPlaceholder: "Dars haqida...",
      studentsCount: "Talabalar",

      // Courses
      coursesTitle: "Kurslar",
      addCourse: "Kurs qo'shish",
      courseModalAdd: "Kurs qo'shish",
      courseModalEdit: "Kursni tahrirlash",
      courseModalAddSubtitle: "Yangi kurs yaratish uchun ma'lumotlarni kiriting.",
      courseModalEditSubtitle: "Kurs ma'lumotlarini yangilash.",
      courseNameLabel: "Kurs nomi",
      courseNamePlaceholder: "Kurs nomini kiriting",
      courseDurationLabel: "Kurs davomiyligi",
      courseDurationPlaceholder: "Oylar sonini kiriting",
      lessonDurationLabel: "Dars davomiyligi",
      lessonDurationPlaceholder: "Dars davomiyligini kiriting",
      courseDescLabel: "Tavsif",
      courseDescPlaceholder: "Kurs haqida ma'lumot",
      archiveCourses: "Arxivlangan kurslar",
      noArchivedCourses: "Arxivlangan kurslar yo'q",
      courseDeleteConfirm: "Kursni o'chirish",
      courseDeleteMsg: "Rostdan ham bu kursni o'chirishni hohlaysizmi?",
      month: "oy",

      // Rooms
      roomsTitle: "Xonalar",
      addRoom: "Xonani qo'shish",
      roomModalAdd: "Xonani qo'shish",
      roomModalEdit: "Xonani tahrirlash",
      roomNameLabel: "Xona nomi",
      roomNamePlaceholder: "Xona nomini kiriting",
      roomCapacityLabel: "Sig'imi",
      roomCapacityPlaceholder: "Sig'imni kiriting",
      archiveRooms: "Arxivlangan xonalar",
      noArchivedRooms: "Arxivlangan xonalar yo'q",
      roomDeleteConfirm: "Xonani o'chirish",
      roomDeleteMsg: "Rostdan ham bu xonani o'chirishni hohlaysizmi?",

      // Staff
      staffTitle: "Xodimlar",
      staffComingSoon: "Xodimlar bo'limi tez orada qo'shiladi.",

      // Gifts
      giftsTitle: "Sovg'alar",

      // Not Found
      notFound: "Siz qidirgan sahifa mavjud emas yoki ko'chirilgan.",
      notFoundBtn: "Asosiy sahifaga qaytish",

      // Create Homework
      createHomeworkTitle: "Uyga vazifa qo'shish",
      homeworkTopic: "Mavzu",
      homeworkTopicPlaceholder: "Vazifa mavzusini kiriting",
      homeworkDescPlaceholder: "Vazifa tavsifini kiriting",

      // Toast
      errorGeneral: "Xatolik yuz berdi",
      successGeneral: "Muvaffaqiyatli",
    },

    ru: {
      // Login
      loginLabel: "Логин",
      loginPlaceholder: "Введите логин",
      passwordLabel: "Пароль",
      passwordPlaceholder: "Введите пароль",
      loginBtn: "Войти",
      loginError: "Неверный логин или пароль",
      loginSuccess: "Успешный вход",
      copyright: "Copyright © 2024 Najot Ta'lim",
      logout: "Выйти",
      loading: "Загрузка",

      // Sidebar / Nav menu
      menu: ["Главная", "Учителя", "Группы", "Студенты", "Подарки", "Управление"],
      subscription: "Подписка",
      subscriptionExpired: "Ваша подписка истекла",
      subscriptionRenew: "Обновить подписку",
      darkMode: "Тёмный",
      lightMode: "Светлый",

      // Management sidebar
      courses: "Курсы",
      rooms: "Кабинеты",
      staff: "Сотрудники",
      coin: "Монеты",
      sendMessage: "Отправить сообщение",

      // Common buttons
      add: "Добавить",
      save: "Сохранить",
      cancel: "Отмена",
      edit: "Редактировать",
      delete: "Удалить",
      archive: "Архив",
      restore: "Восстановить",
      search: "Поиск",
      filter: "Фильтр",
      refresh: "Обновить",
      send: "Отправить",
      sending: "Отправляется...",
      yes: "Да",
      close: "Закрыть",
      back: "Назад",
      statistics: "Статистика",
      previous: "← Назад",
      next: "Вперёд →",

      // Confirm dialog
      confirmDelete: "Подтвердить удаление",
      confirmDeleteMsg: "Вы действительно хотите удалить?",

      // Common labels
      name: "Название",
      fullName: "Ф.И.О",
      phone: "Телефон",
      email: "Email",
      address: "Адрес",
      password: "Пароль",
      birthDate: "Дата рождения",
      group: "Группа",
      groups: "Группы",
      date: "Дата",
      actions: "Действия",
      status: "Статус",
      active: "АКТИВНЫЙ",
      inactive: "НЕАКТИВНЫЙ",
      noData: "Данные отсутствуют",
      loading2: "Загрузка...",

      // Dashboard
      dashboardGreeting: "Привет",
      dashboardWelcome: "Добро пожаловать в Najot CRM!",
      activeStudents: "Активные студенты",
      groupsCount: "Группы",
      monthPayments: "Оплаты за текущий месяц",
      debtors: "Должники",
      frozen: "Замороженные",
      archived: "В архиве",
      monthlyPayments: "Оплаты за текущий месяц",
      annualProfit: "Годовая прибыль",
      schedule: "Расписание занятий",

      // Teachers
      teachersTitle: "Учителя",
      teachersSubtitle: "На этой странице вы найдёте список учителей и их данные.",
      addTeacher: "Добавить учителя",
      teacherAdded: "Учитель добавлен",
      teacherUpdated: "Учитель обновлён",
      teacherDeleted: "Учитель удалён",
      teacherDeleteConfirm: "Удаление учителя",
      teacherDeleteMsg: "Вы действительно хотите удалить этого учителя?",
      archiveTeachers: "Архивированные учителя",
      noArchivedTeachers: "Архивированных учителей нет",
      teacherModalAdd: "Добавить учителя",
      teacherModalEdit: "Редактировать учителя",
      teacherModalAddSubtitle: "Здесь вы можете добавить нового учителя.",
      teacherModalEditSubtitle: "Здесь вы можете обновить данные учителя.",

      // Students
      studentsTitle: "Студенты",
      studentsSubtitle: "На этой странице представлен список студентов и их данные.",
      addStudent: "Добавить студента",
      studentAdded: "Студент добавлен",
      studentUpdated: "Студент обновлён",
      studentDeleted: "Студент удалён",
      studentDeleteConfirm: "Удаление студента",
      studentDeleteMsg: "Вы действительно хотите удалить этого студента?",
      archiveStudents: "Архивированные студенты",
      noArchivedStudents: "Архивированных студентов нет",
      studentModalAdd: "Добавить студента",
      studentModalEdit: "Редактировать студента",

      // Groups
      groupsTitle: "Группы",
      addGroup: "Добавить группу",
      groupActivated: "Группа активирована",
      groupDeactivated: "Группа деактивирована",
      groupDeleteConfirm: "Удаление группы",
      groupDeleteMsg: "Вы действительно хотите удалить эту группу?",
      archiveGroups: "Архивированные группы",
      archiveGroupsSubtitle: "Список архивированных групп",
      groupModalAdd: "Добавить группу",
      groupModalAddSubtitle: "Введите данные для создания новой группы.",
      course: "Курс",
      duration: "Продолжительность",
      lessonTime: "Время занятий",
      room: "Кабинет",
      teacher: "Учитель",
      students2: "Студенты",
      teacher2: "Учитель",
      maxStudents: "Макс. студентов",
      description: "Описание",
      startDate: "Дата начала",
      daysOfWeek: "Дни занятий",
      startTime: "Время занятий",
      groupName: "Название группы",
      courseName: "Название курса",
      roomName: "Название кабинета",
      courseDuration: "Продолжительность курса",
      lessonDuration: "Продолжительность урока",
      studentCount: "Количество студентов",
      mentors: "Менторы",
      groupParams: "Параметры группы",
      direction: "Направление",
      avgAge: "Средний возраст",
      capacity: "Вместимость",
      currentStudents: "Текущие студенты",
      totalLessons: "Всего уроков",
      lessonSchedule: "Расписание занятий",
      currentMonth: "Текущий месяц",
      showAll: "Показать все",
      hide: "Скрыть",
      showMore: "Показать ещё",
      addStudentToGroup: "Добавить студента",
      addStudentToGroupSubtitle: "Выберите студентов для группы",
      alreadyInGroup: "В группе",
      studentAdding: "Добавляется...",
      studentAddSuccess: "студентов успешно добавлено",
      studentAddError: "Ошибка при добавлении студента",
      mentors: "Менторы",
      noStudentsAdded: "Студенты не добавлены",

      // Group Detail tabs
      groupInfo: "Информация",
      groupLessons: "Уроки группы",
      academicAttendance: "Академическая посещаемость",
      homework: "Домашнее задание",
      videos: "Видео",
      exams: "Экзамены",
      journal: "Журнал",

      // Homework
      homeworkTitle: "Домашнее задание",
      topic: "Тема",
      deadline: "Срок сдачи",
      givenTime: "Дата выдачи",
      lessonDate: "Дата урока",
      studentName: "Имя студента",
      submittedAt: "Время отправки ДЗ",
      pending: "Ожидающие",
      rejected: "Отклонённые",
      accepted: "Принятые",
      notDone: "Не выполнено",
      checkHomework: "Проверка домашнего задания",
      homeworkDesc: "Домашнее задание",
      comment: "Комментарий",
      commentPlaceholder: "Напишите комментарий студенту (необязательно)",
      ball: "Балл",
      passScore: "Проходной балл: 60",
      acceptInfo: "60–100 баллов — Принято.",
      rejectInfo: "0–59 баллов — Отклонено.",
      studentComment: "Комментарий студента:",
      uploadedFiles: "Загруженные файлы:",
      submittedTime: "Время сдачи",
      filesCount: "Кол-во файлов",
      loadError: "Данные не загружены. Обновите страницу.",
      serverError: "Ошибка сервера",
      errorOccurred: "Произошла ошибка. Попробуйте снова.",

      // Videos
      videoName: "Название видео",
      lessonName: "Название урока",
      addedTime: "Добавлено",
      size: "Размер",
      noVideos: "Видео не найдены",
      addVideo: "Добавить видео",
      uploadVideo: "Нажмите для загрузки или перетащите файл сюда",
      uploadFormats: ".mp4, .webm, .mpeg, .avi, .mkv, .m4v, .mov",
      uploadFiles: "Загрузить файлы",
      uploading: "Загружается...",
      selectLesson: "Выберите урок",

      // Lessons
      lessonInfo: "Информация",
      lessonDay: "День занятия",
      lessonStatus: "Статус",
      lessonNotDone: "Урок не проведён",
      attendance: "Посещаемость и ввод темы",
      byPlan: "По учебному плану",
      other: "Другое",
      topicLabel: "Тема",
      topicPlaceholder: "Введите тему...",
      selectTopic: "Выберите тему...",
      lessonDescPlaceholder: "О занятии...",
      studentsCount: "Студенты",

      // Courses
      coursesTitle: "Курсы",
      addCourse: "Добавить курс",
      courseModalAdd: "Добавить курс",
      courseModalEdit: "Редактировать курс",
      courseModalAddSubtitle: "Введите данные для создания нового курса.",
      courseModalEditSubtitle: "Обновить данные курса.",
      courseNameLabel: "Название курса",
      courseNamePlaceholder: "Введите название курса",
      courseDurationLabel: "Продолжительность курса",
      courseDurationPlaceholder: "Введите количество месяцев",
      lessonDurationLabel: "Продолжительность урока",
      lessonDurationPlaceholder: "Введите продолжительность",
      courseDescLabel: "Описание",
      courseDescPlaceholder: "Информация о курсе",
      archiveCourses: "Архивированные курсы",
      noArchivedCourses: "Архивированных курсов нет",
      courseDeleteConfirm: "Удаление курса",
      courseDeleteMsg: "Вы действительно хотите удалить этот курс?",
      month: "мес.",

      // Rooms
      roomsTitle: "Кабинеты",
      addRoom: "Добавить кабинет",
      roomModalAdd: "Добавить кабинет",
      roomModalEdit: "Редактировать кабинет",
      roomNameLabel: "Название кабинета",
      roomNamePlaceholder: "Введите название кабинета",
      roomCapacityLabel: "Вместимость",
      roomCapacityPlaceholder: "Введите вместимость",
      archiveRooms: "Архивированные кабинеты",
      noArchivedRooms: "Архивированных кабинетов нет",
      roomDeleteConfirm: "Удаление кабинета",
      roomDeleteMsg: "Вы действительно хотите удалить этот кабинет?",

      // Staff
      staffTitle: "Сотрудники",
      staffComingSoon: "Раздел сотрудников скоро будет добавлен.",

      // Gifts
      giftsTitle: "Подарки",

      // Not Found
      notFound: "Запрашиваемая страница не найдена или перемещена.",
      notFoundBtn: "На главную",

      // Create Homework
      createHomeworkTitle: "Добавить домашнее задание",
      homeworkTopic: "Тема",
      homeworkTopicPlaceholder: "Введите тему задания",
      homeworkDescPlaceholder: "Введите описание задания",

      // Toast
      errorGeneral: "Произошла ошибка",
      successGeneral: "Успешно",
    }
  };

  const t = T[lang];

  return (
    <AppContext.Provider value={{ dark, toggleDark, lang, toggleLang, t }}>
      {children}
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);
